// 来源: https://json.schemastore.org/claude-code-settings.json
export const CLAUDE_CODE_DESCRIPTIONS: Record<string, string> = {
  env: "环境变量，键名匹配 ^[A-Z_][A-Z0-9_]*$",
  permissions: "工具执行权限控制",
  "permissions.allow": "允许自动执行的操作规则列表",
  "permissions.deny": "禁止执行的操作规则列表",
  "permissions.ask": "每次需要用户确认的操作规则列表",
  "permissions.defaultMode": "默认权限模式 (acceptEdits/plan/delegate/dontAsk)",
  "permissions.disableBypassPermissionsMode": "禁止绕过权限提示",
  "permissions.additionalDirectories": "纳入权限范围的额外目录",
  enabledPlugins: "已启用的插件，格式为 pluginName@marketplace",
  extraKnownMarketplaces: "额外的插件市场源定义",
  pluginConfigs: "各插件的运行时配置",
  effortLevel: "Opus 4.6 自适应推理深度 (low/medium/high)",
  model: "覆盖默认使用的模型",
  availableModels: "限制用户可选择的模型列表",
  modelOverrides: "将 Anthropic 模型 ID 映射到 Provider 特定 ID",
  fastMode: "启用 Opus 4.6 快速模式",
  hooks: "自定义命令钩子 (PreToolUse/PostToolUse/Stop 等)",
  statusLine: "自定义状态栏显示命令",
  sandbox: "沙箱执行配置",
  language: "Claude 响应的首选语言",
  autoMemoryEnabled: "启用自动记忆保存到 .claude/memory/",
  autoUpdatesChannel: "更新频道 (stable/latest)",
  cleanupPeriodDays: "聊天记录保留天数 (0=禁用清理)",
  includeGitInstructions: "包含内置 git commit 和 PR 工作流指令",
  respectGitignore: "@ 文件选择器是否遵循 .gitignore",
  outputStyle: "助手响应的输出风格",
  attribution: "Git 归属信息配置",
  plansDirectory: "计划文件存储目录",
  worktree: "Git worktree 配置",
  teammateMode: "Agent 团队模式 (auto/in-process/tmux)",
  apiKeyHelper: "输出认证值的脚本路径",
  claudeMdExcludes: "排除加载的 CLAUDE.md glob 模式",
};

// 来源: https://developers.openai.com/codex/config-reference
export const CODEX_DESCRIPTIONS: Record<string, string> = {
  model: "默认使用的 AI 模型 ID",
  model_provider: "模型提供商 ID",
  model_reasoning_effort: "推理努力程度 (minimal/low/medium/high/xhigh)",
  model_context_window: "可用上下文窗口 Token 数",
  model_verbosity: "输出详细程度 (low/medium/high)",
  sandbox_mode: "沙箱模式 (read-only/workspace-write/danger-full-access)",
  approval_policy: "审批策略 (untrusted/on-request/never)",
  approvals_reviewer: "审批路由 (user/guardian_subagent)",
  web_search: "Web 搜索 (disabled/cached/live)",
  model_auto_compact_token_limit: "自动压缩上下文的 Token 阈值",
  model_instructions_file: "自定义指令文件路径",
  model_providers: "自定义模型提供商配置",
  "model_providers.name": "提供商显示名称",
  "model_providers.base_url": "API 基础 URL",
  "model_providers.experimental_bearer_token": "API 认证令牌",
  "model_providers.http_headers": "自定义 HTTP 请求头",
  "model_providers.env_key": "API Key 环境变量名",
  "model_providers.wire_api": "API 协议类型 (chat/responses)",
  "model_providers.requires_openai_auth": "是否需要 OpenAI 兼容认证",
  "model_providers.request_max_retries": "请求最大重试次数",
  "model_providers.stream_max_retries": "流式响应最大重试次数",
  "model_providers.stream_idle_timeout_ms": "流式响应空闲超时 (ms)",
  profiles: "命名配置集，通过 --profile 切换",
  "profiles.model": "该 Profile 的模型 ID",
  "profiles.model_provider": "该 Profile 的提供商",
  projects: "项目级信任设置",
  "projects.trust_level": "信任级别 (trusted/untrusted)",
  features: "功能开关 (shell_tool/multi_agent/web_search/memories 等)",
  mcp_servers: "MCP 服务器配置",
  agents: "多 Agent 并发和嵌套控制",
  "agents.max_threads": "最大并发 Agent 线程数 (默认 6)",
  "agents.max_depth": "Agent 嵌套深度 (默认 1)",
  tui: "终端 UI 配置",
  history: "会话历史设置",
  memories: "记忆系统配置",
  permissions: "文件系统和网络访问权限",
  otel: "OpenTelemetry 可观测性配置",
};

// 来源: https://opencode.ai/docs/config/
export const OPENCODE_DESCRIPTIONS: Record<string, string> = {
  $schema: "JSON Schema URL，提供编辑器自动补全和校验",
  model: "默认主模型，格式为 provider/model-id",
  small_model: "轻量级任务模型",
  share: "会话分享模式 (manual/auto/disabled)",
  snapshot: "启用基于内部 git 的变更追踪",
  autoupdate: "自动更新行为",
  default_agent: "未指定时使用的默认 Agent",
  provider: "模型提供商配置",
  "provider.whitelist": "允许使用的模型 ID 白名单",
  "provider.options": "API 连接参数 (apiKey/baseURL)",
  "provider.models": "模型定义 (能力声明/参数限制)",
  "provider.npm": "AI SDK 的 npm 包名",
  "provider.env": "所需环境变量列表",
  agent: "自定义 Agent 定义 (description/model/prompt/tools)",
  tools: "启用/禁用特定工具 (write/bash 等)",
  command: "自定义命令模板",
  formatter: "代码格式化器配置",
  permission: "工具调用权限审批规则",
  server: "opencode serve/web 服务器配置",
  mcp: "Model Context Protocol 服务器连接",
  compaction: "上下文窗口管理和自动压缩",
  watcher: "文件变更监控忽略规则",
  experimental: "实验性功能开关",
  plugin: "npm 插件标识符列表",
  instructions: "指令文件路径模式",
  disabled_providers: "禁用的 Provider 列表",
  enabled_providers: "启用的 Provider 白名单",
};
